services:
  exchange:
    image: rabbitmq:4-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
  cache:
    image: valkey/valkey-bundle:8
    ports:
      - "6379:6379"